<template>
  <div>
  <h1 id="02-coronary-artery-disease">02: Coronary Artery Disease</h1>
<p><img src="static/img/AMD_into.jpeg" alt="optional caption text"></p>
<h2 id="description">Description</h2>
<h1 id="coronary-artery-disease-cad-is-a-cardiovascular-disease-in-which-blood-flow-to-the-heart-is-disrupted-1-2-it-is-the-number-one-cause-of-death-in-industrialized-societies-including-the-united-states-3-in-2010-1-out-of-every-6-deaths-in-the-u-s-was-caused-by-cad-3-the-most-common-process-for-cad-is-atherosclerosis-in-which-plaque-builds-up-on-the-walls-of-an-individual-39-s-coronary-arteries-which-leads-to-the-hardening-and-narrowing-of-these-vessels-over-time-4-">Coronary artery disease (CAD) is a cardiovascular disease in which blood flow to the heart is disrupted.^1,2^  It is the number one cause of death in industrialized societies, including the United States.^3^ In 2010, 1 out of every 6 deaths in the U.S. was caused by CAD.^3^  The most common process for CAD is atherosclerosis, in which plaque builds up on the walls of an individual&#39;s coronary arteries, which leads to the hardening and narrowing of these vessels over time.^4^</h1>
<h2 id="subtypes">Subtypes</h2>
<p>CAD can be divided into several subtypes: asymptomatic, angina pectoris, and myocardial infarction.^2^  Asymptomatic CAD occurs when an individual&#39;s cardiac vessels have blockage, but that individual does not have pain or other symptoms of disease.  Over time, asymptomatic CAD may progress to angina pectoris and myocardial infarction.^3^</p>
<p>Angina pectoris, or chest pain, occurs when the heart muscle does not receive as much blood as it needs due to blockage of the arteries.  An individual with angina may experience feelings of pressure, fullness, squeezing, or pain in their chest region or in other regions including the neck, jaw, shoulder, back, or arm.  Angina may be further divided into stable and unstable subtypes. In stable angina, an individual experiences multiple episodes of angina with similar frequency, intensity, and duration. In cases of unstable angina, an individual with a previously stable condition may experience angina with increasing frequency and severity.  Unstable angina requires medical attention as it signals that myocardial infarction is likely imminent.^1,4,5^</p>
<p>Myocardial infarction, or heart attack, occurs when blood flow to the heart is either severely diminished or totally cut off.  This can occur when a plaque breaks, which causes a clot to form around the plaque.  The clot may block the blood vessel, depriving the heart of oxygen and leading to damage or death of heart muscle.  The severity of a heart attack depends on the particular artery that is blocked and the amount of time between the event and treatment.  With proper treatment and lifestyle changes, many individuals who experience a heart attack may prevent additional damage to their hearts in the future.^1,4,5^</p>
<h2 id="treatment-and-management">Treatment and Management</h2>
<p>An individual with CAD may be treated with a variety of medications, including anticoagulants and drugs that change the way the heart beats.  For those with more advanced disease, surgical procedures including angioplasty, bypass, or stenting may be required.  In addition to medications and surgical options, lifestyle changes such as avoiding tobacco, becoming more active, and making good nutritional choices.1</p>
<h1 id="-risk-factors-"><strong>Risk Factors</strong></h1>
<h2 id="inheritance-and-family-history">Inheritance and Family History</h2>
<p>CAD is a multifactorial condition, meaning that both genetic and environmental factors combine to affect risk to develop the disease. Heritability is a term used to estimate the amount that genetic factors contribute to the difference in disease risk among individuals. For CAD, heritability is estimated to be between 50 and 60%, meaning that between 50 and 60 percent of the variability in disease risk among individuals is due to genetic differences. Family history information as well as genetic testing may be able to identify some of the genetic risk factors that contribute to the heritability of CAD.^6,7,8,9^</p>
<p>Family studies have suggested that individuals who have a first degree relative (parent, sibling, or child) with CAD are at an increased risk to develop the condition themselves. The precise increase in risk is not well-defined, but reports suggest there is up to a three fold increase in likelihood for these individuals to develop CAD.  It is estimated that the the risk for an individual to develop CAD increases with greater numbers of affected close relatives and younger onset of disease in these relatives.^4,7,8,9^</p>
<h2 id="other-risk-factors">Other Risk Factors</h2>
<p>A number of other factors are known to be associated with the risk to develop CAD. The likelihood of developing CAD increases with age. The risk of CAD is higher in African American populations than Caucasian populations and lower in the Hispanic population.  The average age at which CAD develops in women is approximately 7-10 years later than men.^3,5,10^</p>
<p>Cigarette smoking is a well-described risk factor for the development of CAD, with the likelihood of developing CAD increased by approximately two times among smokers.  This is due to the fact that smoking can trigger a buildup of plaque in a person&#39;s arteries and increase the risk of blood clots forming in those narrowed arteries. The amount and duration of smoking affects the degree to which this risk is increased. Importantly, studies have shown that individuals who stop smoking almost immediately begin to see risk reduction and return to nearly baseline population risk for CAD over time.1,11</p>
<p>Having high blood pressure is also a risk factor for developing CAD, as it causes the muscle of the heart to become thicker and stiffer due to overwork.  In addition to high blood pressure, high blood cholesterol can also increase a person&#39;s risk for CAD by increasing the likelihood of plaque formation.  Both of these factors can be influenced by a person&#39;s lifestyle in terms of activity level and diet.^1, 11^</p>
<p>Another risk factor for CAD is diabetes mellitus.  The risk is lower if a person&#39;s blood sugar levels are under control.  Over ⅔ of people over the age of 65 die from some form of heart disease, so it is critical for those with diabetes to manage their condition carefully and work to reduce other risk factors.^1,11^</p>
<p>Many studies have demonstrated that low physical activity and obesity are also risk factors for the development of CAD. In fact, people who are inactive have nearly twice the risk to develop CAD as those who are more active. Fortunately, risk reduction can be seen even with modest amounts of physical activity; as an individual&#39;s activity level increases, their risk decreases.  The amount that obesity alone contributes to risk for coronary artery disease is unclear; however, it is linked to other risk factors such as high blood pressure and high cholesterol.  A healthy diet can decrease a person&#39;s risk for CAD by affecting other risk factors such as obesity, cholesterol, and blood pressure.^1,11^</p>
<p>It is important to keep in mind that many of these environmental and lifestyle risk factors can be changed in order to lower risk.  A person&#39;s risk increases further with each additional factor modified, so addressing even one area can begin to lower overall risk.  Because many of these risk factors are linked together by lifestyle habits, the American Heart Association recommends that the best way for a person to lower their total risk for CAD is to avoid tobacco, become more active, and choose good nutrition.^1^</p>
<h2 id="genetic-risk-factors">Genetic Risk Factors</h2>
<p>Below is a summary of several <em>selected*</em> genetic variants which have been identified as influencing a person&#39;s risk for coronary artery disease.</p>
<p><strong>NOTE: The information appearing in all tables are samples and will be customized for each participant&#39;s genotype.</strong></p>
<p>|THIS IS A VARIANT TABLE|WITH SOME STUFF IN IT |:honeybee:|</p>
<p><strong>**</strong> Rheumatoid Arthritis**</p>
<h1 id="-overview-"><strong>Overview</strong></h1>
<h2 id="description">Description</h2>
<p>Rheumatoid arthritis (RA) is an autoimmune disorder primarily characterized by chronic joint inflammation, especially in the smaller joints of the feet and hands. Over time, this inflammation can cause joint damage and lead to limitations on movement and activity. RA can also lead to inflammation of other tissues as well as weight loss, anemia, a low grade fever, and a decrease in energy.^1^ RA is thought to affect up to 1% of the population worldwide.2 Most individuals develop symptoms in mid- to late adulthood, and, often, symptoms will appear and subside in a pattern of flares and remissions throughout a person&#39;s lifetime.^1^</p>
<h2 id="subtypes">Subtypes</h2>
<p>RA is typically divided into two subtypes: seropositive and seronegative. Individuals with seropositive RA (approximately 60-80% of those affected) have a particular antibody present in their blood that is thought to initiate an immune response to body tissues and cause RA symptoms. The presence of the anti-citrullinated protein antibody (ACPA) in a blood test can confirm a diagnosis of RA. It also may be detected in individuals without RA symptoms up to 5 to 10 years before signs of the condition appear.^3^</p>
<p>For the remainder of individuals with RA, neither ACPA nor a related antibody called rheumatoid factor is found in the blood, yet clinical symptoms are present. This type of RA is referred to as seronegative. A diagnosis of RA can be confirmed in these cases by clinical presentation as well as X-rays showing characteristic bone and joint damage. Knowing the subtype of an individual&#39;s RA diagnosis is important, as many treatments for seropositive RA are not as effective in those with seronegative RA.^4^</p>
<p>Although seropositive and seronegative forms of RA have long been used to categorize the condition, physicians and researchers now understand there are probably many more subtypes of RA based on whether they occur along with other types of autoimmune disorders.^4^</p>
<p>Juvenile rheumatoid arthritis (JRA) is a particularly complex form of rheumatoid arthritis that causes symptom onset in children under the age of 17. While many of the symptoms are similar to the more common form of RA, JRA can also create growth problems as a result of bone and joint damage in growing children. It remains unclear whether JRA is a subtype of RA or actually a separate disease process. Risk factors included in this chapter are known to be associated with rheumatoid arthritis but not necessarily the juvenile form.^4^</p>
<h2 id="treatment-and-management">Treatment and Management</h2>
<p>For someone diagnosed with RA, medications both to manage pain as well as slow the progression of disease may be recommended. Some of these medications have side effects, including but not limited to suppression of parts of the immune system, that can cause other medical problems. In some cases, surgery may be necessary to replace severely damaged joints.^5^</p>
<h1 id="-risk-factors-"><strong>Risk Factors</strong></h1>
<h2 id="inheritance-and-family-history">Inheritance and Family History</h2>
<p>RA is a multifactorial condition, meaning that both genetic and environmental factors combine to affect risk to develop the disease.2 Heritability is a term used to estimate the amount that genetic factors contribute to the difference in disease risk among individuals. For seropositive RA, heritability is estimated to be approximately 50%,, meaning that around 50% of the variability in disease risk among individuals is due to genetic differences.6 This amount is lower in seronegative RA, which is thought to have a heritability of approximately 20%.6 Family history information as well as genetic testing may be able to identify some of the genetic risk factors that contribute to the heritability of RA.^7^</p>
<p>Family studies have suggested that individuals who have  a first degree relative (parent, sibling, or child) with RA are at an increased risk to develop the condition themselves. The precise increase in risk is not well-defined, but reports suggest there is a four to eight fold increase in  likelihood for these individuals to develop RA, with the gender of the affected family member modulating this risk.^8^</p>
<h2 id="genetic-risk-factors">Genetic Risk Factors</h2>
<p>Below is a summary of several <em>selected</em> genetic variants which have been identified as influencing a person&#39;s risk for macular degeneration.</p>
<p>TABLE</p>
<h2 id="other-risk-factors">Other Risk Factors</h2>
<p>A number of other factors are known to be associated with the risk to develop RA. The likelihood of developing RA increases with age, especially once individuals are over the age of 34, with a peak in the fifth decade.2,9 RA is less likely in those identifying as Asian or Hispanic when compared to Caucasians and African Americans.9 Women are two to three times more likely to develop RA than men.^2^</p>
<p>Smoking is a well-described risk factor for RA.2 Smokers are approximately one and one half to two times more likely to develop seropositive RA, and an increased risk has been shown to persist even among former smokers.10 Obesity has also been shown to increase the risk to develop RA.11 Certain changes in a person&#39;s gut bacteria, or intestinal microbiome, have been implicated in RA risk as well, though these are not yet well-understood.12 In addition, infection with certain periodontal diseases and occupational exposure to silica dust have also each been considered as possible RA risk factors.13 Furthermore, lower socioeconomic status and fewer years of education have been associated with an increased risk of inflammation, which is a key to the disease process of RA.^2^</p>
</div>
</template>
